/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.JOptionPane;
import static jframe.DBconnect.con;

/**
 *
 * @author arkan
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    //insert values into akun table
    public void insertSignupDetails(){
        String id = txt_NUPTK_signupp.getText();
        String nama = txt_username_signup.getText();
        String pwd = txt_pass_signup.getText();
        String email = txt_email.getText();
        
        try {
            Connection con = DBconnect.getConnection();
            String sql = "insert into akun(id,nama,password,email) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
                    
            pst.setString(1, id);
            pst.setString(2, nama);
            pst.setString(3, pwd);
            pst.setString(4, email);
            
            int updatedRowCount = pst.executeUpdate();
            
            if (updatedRowCount > 0) {
                JOptionPane.showMessageDialog(this, "Berhasil Daftar");
                Login page = new Login();
                page.setVisible(true);
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(this, "Gagal Daftar");
            }
            
            }catch (Exception e){
                e.printStackTrace();
        }
    }
    
    //validasi data
    
    public boolean validateSignup(){
        String id = txt_NUPTK_signupp.getText();
        String nama = txt_username_signup.getText();
        String pwd = txt_pass_signup.getText();
        String email = txt_email.getText();
        
        if (id.equals("")){
            JOptionPane.showMessageDialog(this, "NUPTK tidak tersedia");
            return false;
        }
        if (nama.equals("")){
            JOptionPane.showMessageDialog(this, "username tidak tersedia");
            return false;
        }
            if (pwd.equals("")){
            JOptionPane.showMessageDialog(this, "password tidak tersedia");
            return false;
        }
            if (email.equals("")){
            JOptionPane.showMessageDialog(this, "email tidak tersedia");
            return false;
        }
            return true;
    }
    
    //cek duplikasi pada database
    public boolean checkDuplicate(){
        String id = txt_NUPTK_signupp.getText();
        boolean isExist = false;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus","root","");
             
             PreparedStatement pst = con.prepareStatement("select * from akun where id = ? and password = ?");
             pst.setString(1, id);
             ResultSet rs = pst.executeQuery();
             if (rs.next()) {
                isExist = true;
            }else{
                 isExist = false;
             }
             
        } catch (Exception e) {
            e.printStackTrace();
        } 
        return isExist;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_NUPTK_signupp = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_email = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_pass_signup = new app.bolivia.swing.JCTextField();
        txt_username_signup = new app.bolivia.swing.JCTextField();
        jPanel2 = new javax.swing.JPanel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_NUPTK_signupp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_NUPTK_signupp.setPlaceholder("NUPTK");
        txt_NUPTK_signupp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NUPTK_signuppFocusLost(evt);
            }
        });
        txt_NUPTK_signupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NUPTK_signuppActionPerformed(evt);
            }
        });
        jPanel1.add(txt_NUPTK_signupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel1.setText("Welcome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel2.setText("Perpustakaan SD T Putra Harapan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_email.setPlaceholder("Masukkan Email");
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel6.setText("REGISTER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        txt_pass_signup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_pass_signup.setPlaceholder("Masukkan Password");
        jPanel1.add(txt_pass_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        txt_username_signup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_username_signup.setPlaceholder("Nama");
        txt_username_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username_signupActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(153, 153, 255));
        rSMaterialButtonRectangle1.setText("DAFTAR");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 50));

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Kembali");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 260, 370));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 830));

        setSize(new java.awt.Dimension(991, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        if (validateSignup() == true) {
            if (checkDuplicate() == false) {
                insertSignupDetails();
            }else{
                JOptionPane.showMessageDialog(this, "NUPTK telah didaftarkan");
            }
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Login page = new Login();
                page.setVisible(true);
                dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_username_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username_signupActionPerformed
        
    }//GEN-LAST:event_txt_username_signupActionPerformed

    private void txt_NUPTK_signuppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NUPTK_signuppFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NUPTK_signuppFocusLost

    private void txt_NUPTK_signuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NUPTK_signuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NUPTK_signuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private app.bolivia.swing.JCTextField txt_NUPTK_signupp;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_pass_signup;
    private app.bolivia.swing.JCTextField txt_username_signup;
    // End of variables declaration//GEN-END:variables
}
